title: Moonshine Docs
baseurl: /moonshine-docs
theme: minima
header_pages:
  - ecosystem.md
  - getting-started.md
  - session-lifecycle.md
  - rom-lifecycle.md
  - lua-api-v1.md
  - manifest.md
  - variants-and-modes.md
  - menus-configuration.md
  - progression-milestones.md
  - leaderboards.md
  - example-progression-mode.md
exclude:
  - internal
