title: Moonshine Docs
baseurl: /moonshine-docs
theme: minima
header_pages:
  - introduction.md
  - ecosystem.md
  - getting-started.md
  - manifest.md
  - variations-and-modes.md
  - menus-configuration.md
  - progression-milestones.md
  - leaderboards.md
  - best-practices.md
  - example-progression-mode.md
exclude:
  - internal
